### ISSUE TITLE
Failed to load application: No module named honeywrt.core.config 

### ISSUE THREAD

**Issue by zachsis** [CanadianJeff/honeywrt#5]
After installing all dependencies, i'm getting this output.

```
[honeydude@heyhoney honeywrt]$ ./start.sh
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/twisted/application/app.py", line 648, in run
    runApp(config)
  File "/usr/lib64/python2.7/site-packages/twisted/scripts/twistd.py", line 25, in runApp
    _SomeApplicationRunner(config).run()
  File "/usr/lib64/python2.7/site-packages/twisted/application/app.py", line 379, in run
    self.application = self.createOrGetApplication()
  File "/usr/lib64/python2.7/site-packages/twisted/application/app.py", line 444, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/usr/lib64/python2.7/site-packages/twisted/application/app.py", line 455, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/usr/lib64/python2.7/site-packages/twisted/application/service.py", line 411, in loadApplication
    passphrase)
  File "/usr/lib64/python2.7/site-packages/twisted/persisted/sob.py", line 223, in loadValueFromFile
    eval(codeObj, d, d)
  File "honeywrt/core/honeypot.py", line 34, in <module>
    from honeywrt.core.config import config
exceptions.ImportError: No module named honeywrt.core.config


Failed to load application: No module named honeywrt.core.config

```

I can see `config.py` nested under `honeywrt/core/config.py`. so i'm not sure why the import statement isn't working =/. its almost as though the __init__.py files nested below the cloned repo aren't being handled.

**Comment by zachsis** [comment]
not sure if this helps: 

http://stackoverflow.com/questions/9427037/relative-path-not-working-even-with-init-py
